### ISSUE TITLE
Q: Is there a way to pass array parameter?

### ISSUE THREAD

**Issue by ihoro** [reactiverse/reactive-pg-client#102]
It’s totally fine with a query like `select * from user where id = $1;` when you pass Tuple.of(1001) or something. But what about arrays for IN operator like `select * from user where id in ($1)` with a list of user IDs e.g. 1001,1002,1003?

By the way, awesome project!

**Comment by vietj** [comment]
arrays are supported with `Tuple.tuple().addIntArray(new int[] { 1001, 1002, 1003 })`

I think we are missing this in documentation

**Comment by vietj** [comment]
I think also passing an array should be fine (`Tuple.of(new int[] { ... })`), but I haven't tried it.

**Comment by vietj** [comment]
oh really ? the javadoc seems to have it, can you investigate ?

I will release I think 0.8.0 soon anyway

**Comment by ihoro** [comment]
Okay, got it, getDelegate() from rxjava2 and I have addIntArray().

**Comment by vietj** [comment]
at yes, we aim to imoprove that in next version of Vert.x 3.6.0 and these methods should be here

**Comment by ihoro** [comment]
and the same with `master`

**Comment by vietj** [comment]
yes that would be with vertx 3.6.0

**Comment by ihoro** [comment]
Great, looking forward for the updates to start usage of array parameters.
I'm fine with simple workarounds meanwhile.

Thank you for quick replies and support overall.

**Comment by vietj** [comment]
btw can you explain your motivation for using this client instead of others ?

**Comment by vietj** [comment]
we are still in version 0.x.z because we want full support for some features like all PG types for binary and text before being in 1.0.0

**Comment by vietj** [comment]
we are missing specific PG types like geometric types, etc...
