### ISSUE TITLE
Geometric types supports

### ISSUE THREAD

**Issue by vietj** [reactiverse/reactive-pg-client#114]
Add support for all geometric types:

- line
- lseg
- box
- path
- polygon
- circle

Point is already supported : https://github.com/reactiverse/reactive-pg-client/commit/ed3cea20ee2420be072ba6b57b3f9d77cc6e59d4

**Comment by pratikpparikh** [comment]
@vietj Point is a relatively simple object to read/write in binary.  How does one write and complex objects like path?  For example, let's say you have a label (string),  userid (complex type), and json.  I could encode it in a sequence but while reading string can be of variable length?  do we have store the size of the string in the binary as a separate element?  for example, does it mean now I have to store labelLength, label, userid, and json?

**Comment by vietj** [comment]
I think you should go json array and convert stuff to json in this case

**Comment by pratikpparikh** [comment]
So is this correct interpretation of your recommendation? 

//encodePath
binaryEncodeJSONB(Json.create(value.toJson()),buff);

//decodePath
final Json pathJson = binaryDecodeJSONB(len,buff);
final JsonObject pathJsonObject = (JsonObject) vertexJson.value();
return new Vertex(pathJsonObject);

**Comment by vietj** [comment]
what is path ? do you mean geometric path ?

in that's a PG geometric path, then it could use the native representation of path by PG.

**Comment by vietj** [comment]
this issue is about supporting geometric types for this client :-)

**Comment by pratikpparikh** [comment]
@vietj I am sorry but thought this conversation still be useful regardless to the contributor who might want to help.  I am also planning to pick that up, as soon as I finish what with my release work.

**Comment by vietj** [comment]
agreed @pratikpparikh
