### ISSUE TITLE
Example use of rx'ified version of the client

### ISSUE THREAD

**Issue by kiddouk** [reactiverse/reactive-pg-client#119]
Hello,

I am trying to use the rx'ified version of the client and I am interested in the streaming functionality that this driver is offering.
However, I cannot seem to find a proper way to fetch the data when using rxQuery.
I turn the single emitted into an observable and was hopping to either:

1) flatMap to Observable.from(PgRowSet) (Potentially accepting that the full data set would have to be loaded first)

or 

2) flatMap to PgRowSet.createStream and hoping to get an observable back.

Now that I know that none of that is possible, how can I use rxQuery to achieve the retrieving of the results in a stream and non-stream way?

Cheers.

**Comment by vietj** [comment]
@kiddouk you need to use the `PgPreparedQuery` and thus you need a connection to achieve it:

```
    Flowable<Row> flowable = pool.rxGetConnection()
      .flatMapPublisher(conn -> conn.rxPrepare("my query")
        .flatMapPublisher(pq -> {
          PgStream<Row> stream = pq.createStream(100, Tuple.of("some", "args"));
          return stream.toFlowable();
        }));
```

**Comment by kiddouk** [comment]
For the ones wanting an rxjava 1.x example

```kotlin
pool.rxGetConnection()
    .flatMap { conn -> conn.rxPrepare("query") }
    .flatMapObservable { preparedQuery -> preparedQuery.createStream(20, Tuple.of(arg)).toObservable() }
```

**Comment by vietj** [comment]
I'll add specific documentation for RxJava

**Comment by vietj** [comment]
I've added documentation for this, it should be deployed with the next release
