### ISSUE TITLE
Cursor Issue

### ISSUE THREAD

**Issue by sstubbs** [reactiverse/reactive-pg-client#121]
I have been trying out this driver and it has been working well with vertx and I can retrieve all results well. I do have memory issues so I tried the streaming option which only loaded the first results and no others. So I have moved one step back to the cursors and I am getting the same problem. With the following I only receive the first values. The while loop runs once where it should run multiple times and even on the first iteration within there are no results.

```
PgPool pool = PgClient.pool(vertx.getDelegate(), options);

        pool.getConnection(ar1 -> {
            if (ar1.succeeded()) {
                PgConnection connection = ar1.result();
                Buffer sql = vertx.fileSystem().readFileBlocking("sql/test.sql");
                connection.prepare(sql.toString(), ar2 -> {
                    if (ar2.succeeded()) {
                        resultHandler.handle(Future.succeededFuture(new JsonObject().put("started", true)));
                        PgPreparedQuery pq = ar2.result();
                        PgCursor cursor = pq.cursor(Tuple.of("test"));

                        cursor.read(5, ar3 -> {
                            PgRowSet rows = ar3.result();
                            JsonArray jsonResults = new JsonArray();
                            PgIterator iterator = rows.iterator();
                            while (iterator.hasNext()) {
                                Row result = iterator.next();
                                jsonResults.add(result);
                            }
                            logger.info(jsonResults);

                            while (cursor.hasMore()) {
                                cursor.read(5, ar4 -> {
                                    PgRowSet rows2 = ar4.result();
                                    JsonArray jsonResults2 = new JsonArray();

                                    PgIterator iterator2 = rows2.iterator();
                                    while (iterator2.hasNext()) {
                                        Row result2 = iterator2.next();
                                        jsonResults2.add(result2);
                                    }
                                    logger.info(jsonResults2);
                                });
                            }
                        });
                    }
                    else {
                        resultHandler.handle(ServiceException.fail(CONNECTION_FAILED, ar2.cause().getMessage()));
                    }
                });
```

**Comment by vietj** [comment]
can you write a test (reproducer) so I can have a look at it easily ?

**Comment by sstubbs** [comment]
Sure I will get one done tomorrow.

**Comment by vietj** [comment]
thanks, that will help and it will also be used as unit-test so if you can write it as a pg-client unit test it's even better

**Comment by sstubbs** [comment]
I see you already have some tests here for the cursors https://github.com/reactiverse/reactive-pg-client/blob/master/src/test/java/io/reactiverse/pgclient/PreparedStatementTestBase.java. Do these run against an actual database or are they mocked somehow? I'm just trying to work out what I should add.

**Comment by vietj** [comment]
@sstubbs they run against a real postgres started with embedded postgres project

**Comment by sstubbs** [comment]
OK I will go through this section and compare it to what I have done. Perhaps it's an issue on my end otherwise I will add the test.

**Comment by vietj** [comment]
@sstubbs any news about this ?

**Comment by vietj** [comment]
@yonigibbs I believe it's quite solid and production read, if there are issues we fix them as soon as we can and issue fixes (there are people already using it in production).

**Comment by yonigibbs** [comment]
Brilliant!  Just what I wanted hear.  Thanks very much.  Will log issues if any come up.

**Comment by vietj** [comment]
I will simply updte the docuemntation and examples, I think that's enough. It seems complicated wrt to the pg protocol to speculate on the transaction status

**Comment by rac021** [comment]
I have the same issue, . The while ( cursor.hasMore() ) loop runs once. I began a transaction before getting the cursor but this doesn't work ! Any idea ? 

Thanks

**Comment by vietj** [comment]
can you provide a reproducer @rac021 ?

**Comment by rac021** [comment]
@vietj , you can find my reproducer here : https://gist.github.com/rac021/3b0d3a54537bf5174ff7e8bdfd5ef1d6 

You have just to set the **sqlQuery** and **PgConnectOptions** in the main 

Thanks

**Comment by vietj** [comment]
can you open a new issue for this pls with this reproducer ?

**Comment by rac021** [comment]
@vietj Done !

**Comment by vietj** [comment]
thanks a lot
