### ISSUE TITLE
generatedKeys() on PgRowSet

### ISSUE THREAD

**Issue by rodolfodpk** [reactiverse/reactive-pg-client#122]
it has updatedCount() but not generatedKeys()

**Comment by vietj** [comment]
I haven't seen an option to get that from the Postgres protocol... have you any information about how it's possible to obtain it ?

@pmlopes can you help us here ?

**Comment by pmlopes** [comment]
Yes, you need to append " RETURNING *" to the insert statement as the concept of generated keys is artificial at the jdbc api.

**Comment by vietj** [comment]
how are these keys made available by postgres ?

**Comment by pmlopes** [comment]
The returning statement means that the return of this call is a result set with the affected lines, on a insert it will be a single line, on an update it could be the whole affected lines that were updated

**Comment by pmlopes** [comment]
https://www.postgresql.org/docs/current/static/sql-insert.html

> If the INSERT command contains a RETURNING clause, the result will be similar to that of a SELECT statement containing the columns and values defined in the RETURNING list, computed over the row(s) inserted or updated by the command.

**Comment by vietj** [comment]
so as far as I understand it @rodolfodpk should be able to get the keys from the `RowSet` and there is no need to add a `getGeneratedKeys()` specific method, right ?

**Comment by pmlopes** [comment]
Yes.

**Comment by pmlopes** [comment]
The issue with generated keys would be that you would need to parse the query for comments, alias, etc in order to append the `RETURNING` piece in order to get the keys. Since the user wrote the sql then the user has the knowledge to put it on the right place and return what is needed

**Comment by pmlopes** [comment]
This is a powerful construct that can be used with `WITH` statements to perform atomic updates without the need of transactions, so in my opinion the user should have control over it, not be limited by the API

**Comment by vietj** [comment]
so the most appropriate would be to keep the API as is and give examples in the doc of how to proceed ?

**Comment by davecramer** [comment]
The pgjdbc driver rewrites the query and we run into issues occasionally

**Comment by vietj** [comment]
@davecramer what kind of issues ?

**Comment by davecramer** [comment]
if the select already has "with returning" we don't detect it.
IIRC things like CTE's can have with returning embedded.

**Comment by pmlopes** [comment]
@davecramer that is why I was proposing that there's no "magic" on this driver. If a user wants the generated keys, then the user must write the `RETURNING` statement explicitly.

**Comment by vietj** [comment]
I agree @pmlopes , can you provide an example for the documentation ?

**Comment by davecramer** [comment]
makes sense, you should avoid going down the same path as JDBC anyway.
