### ISSUE TITLE
Simplified transaction API

### ISSUE THREAD

**Issue by vietj** [reactiverse/reactive-pg-client#130]
Currently, one need to acquire a connection in order to use a transaction and most importantly release the connection when the transaction ends, which complicates the code for both asynchronous flow and rx flows.

The simplified API allows to create a transaction on the pool, simplifying the acquisition of the transaction. When the transaction ends, the connection is returned to the pool.

```java
    // Acquire a transaction and begin the transaction
    pool.begin(res -> {
      if (res.succeeded()) {

        // Get the transaction
        PgTransaction tx = res.result();

        // Various statements
        tx.query("INSERT INTO Users (first_name,last_name) VALUES ('Julien','Viet')", ar -> {});
        tx.query("INSERT INTO Users (first_name,last_name) VALUES ('Emad','Alblueshi')", ar -> {});

        // Commit the transaction and return the connection to the pool
        tx.commit(ar -> {
          if (ar.succeeded()) {
            System.out.println("Transaction succeeded");
          } else {
            System.out.println("Transaction failed " + ar.cause().getMessage());
          }
        });
      }
    });
```

Here is the Rx version:

```java
    Completable completable = pool
      .rxBegin()
      .flatMapCompletable(tx -> tx
        .rxQuery("INSERT INTO Users (first_name,last_name) VALUES ('Julien','Viet')")
        .flatMap(result -> tx.rxQuery("INSERT INTO Users (first_name,last_name) VALUES ('Emad','Alblueshi')"))
        .flatMapCompletable(result -> tx.rxCommit()));

    completable.subscribe(() -> {
      // Transaction succeeded
    }, err -> {
      // Transaction failed
    });
```

**Comment by pmlopes** [comment]
I'm not sure about this, in a transaction you could have interdependencies between queries, say:

1. insert row
2. insert row using the previously rowid
3. insert row independent from the 2 above

I think that from a scheduling PoV, query 1 and 3 are added to the transaction so the commit handler is awere of them, but the commit handler probably won't know about the 2nd query...

**Comment by vietj** [comment]
well that's just the example that is not correctly written, i.e the current API allows your use case, we just need to execute the second query in the result handler of the first one (like rx does actually).
