### ISSUE TITLE
Typo adPoint in Tuble

### ISSUE THREAD

**Issue by EmadAlblueshi** [reactiverse/reactive-pg-client#139]
https://github.com/reactiverse/reactive-pg-client/blob/176a42e6cbb705c4db3ed56933bd5e3715cdbd0e/src/main/java/io/reactiverse/pgclient/Tuple.java#L665

**Comment by pratikpparikh** [comment]
@EmadAlblueshiI have this corrected in my fork, I noticed this today as well.  It is also in ArrayTuple.java
