### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by davecramer** [reactiverse/reactive-pg-client#143]
INFO: Generated model io.reactiverse.pgclient.Row: io.reactiverse.groovy.pgclient.Row_GroovyExtension
**** COMPILER BUG! REPORT THIS IMMEDIATELY AT http://jira.codehaus.org/browse/MVEL
Expression: @comment{'A library of reusable functions'}@code{

java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

macos

**Comment by vietj** [comment]
compile it with Java 8, it's a Groovy issue with Java > 8
