### ISSUE TITLE
This client support greenplum

### ISSUE THREAD

**Issue by leotu** [reactiverse/reactive-pg-client#148]
The Greenplum is using PG, is it supported ?
https://greenplum.org/

**Comment by vietj** [comment]
can you clarify what "using PG" means ?

**Comment by leotu** [comment]
”Based on PostgreSQL”

**Comment by vietj** [comment]
it is not clear enough, do you have some examples ?

**Comment by vietj** [comment]
ok, that's clear now.

can you tell me how to reproduce your issue (perhaps with docker or with a way to have an accnount) with green plum to look at error ?

**Comment by vietj** [comment]
to be honest it seems the error seems to be because the current client uses case sensitive UTF8 parsing.

so far we only dealt with postgres that sends _UTF8_ string and this seems to send _utf8_ string, so it should be easy to fix.

**Comment by vietj** [comment]
@leotu I've commited this https://github.com/reactiverse/reactive-pg-client/commit/2a3c37a2a7350d46a6432bfbad50a731ab611e05 and I think it should solve the actual problem you encountered, a snapshot should be deployed by the CI in the Sonatype OSS snapshot repository.

**Comment by leotu** [comment]
Great! The "0.10.1-SNAPSHOT" version fixed this problem. I can fetch data without any error.

https://oss.sonatype.org/content/repositories/snapshots/io/reactiverse/reactive-pg-client/

**Comment by vietj** [comment]
awesome, I'll cut a 0.10.1 release soon
