### ISSUE TITLE
support for custom worker thread

### ISSUE THREAD

**Issue by happyyangyuan** [reactiverse/reactive-pg-client#159]
We need all of the postgresql client's asynchronous requests all running in our custom worker thread pool instead of in the vert.x default worker thread pool.

Would you please add support for this?

**Comment by BillyYccc** [comment]
What's the use case here, can you give an example for this?

**Comment by happyyangyuan** [comment]
The most eager need is that I want to set thread context for tracking our business but with vert.x thread pool it is difficult to accomplish that.
And also our business thread pool is fully monitored by our monitor system.

**Comment by BillyYccc** [comment]
I'm afraid this can not be achieved for now because Vert.x does not allow you to create eventloop by your own thread factory instead of VertxThreadFactory or reuse any existed thread pool, maybe you can open issues in https://github.com/eclipse-vertx/vert.x/issues?

**Comment by happyyangyuan** [comment]
Sorry for replying late.
I will describe my use case clearly soon.

**Comment by happyyangyuan** [comment]
@vietj This is my use case
- [pgDatasource use case](https://github.com/xiancloud/xian/blob/master/xian-dao/xian-reactivepgdao/src/main/java/info/xiancloud/dao/async/postgresql/PgXianDatasource.java)
- [pgPool use case with rxJava2](https://github.com/xiancloud/xian/blob/master/xian-dao/xian-reactivepgdao/src/main/java/info/xiancloud/dao/async/postgresql/PgSqlDriver.java)

java code example
```java
pgConnection0
                .rxPreparedQuery(statement, tupleFromArray(preparedParams))
                /*
                // we want make pg connection to use my custom thread
                .observeOn(customScheduler) //this does not work
                todo, it seems that if we use reactive-pg-client, we have to use thread created by vertx.
                 */
                .map(pgRowSet -> {
                    LOG.info("===================  parse updation result set: " + map);
                    return new UpdatingResult().setCount(pgRowSet.rowCount());
                })
                ;
```

ps: we only want a reactive style postgresql client wihtout depending on vertx.io.

**Comment by vietj** [comment]
@happyyangyuan the pg client uses vertx core under the hood

**Comment by vietj** [comment]
but you don't have to use it

**Comment by happyyangyuan** [comment]
@vietj Thx. 
I have been looking for a pure reactive pg client for a while. Do you have any suggestions?

**Comment by vietj** [comment]
what do you mean by suggestion @happyyangyuan ?

**Comment by happyyangyuan** [comment]
@vietj  I mean suggestion of some other reactive postgresql client which is open-source.

**Comment by vietj** [comment]
I think there are a few of them out there, google is your friend
