### ISSUE TITLE
Prepared Statement with Invalid value to Type doesn't bubble error

### ISSUE THREAD

**Issue by hfgbarrigas** [reactiverse/reactive-pg-client#168]
If any value reaches `public static void encodeBinary(DataType id, Object value, ByteBuf buff)` and doesn't match the expected type the error is not propagated and Handler e.g:

`ar -> {
            if (ar.succeeded()) {
                sink.success(ar.result().value());
            } else {
                sink.error(ar.cause());
            }
        }` 

is never called. This leads to hanging resources and subsequently numerous consequences. Is there a way to validate a specific prepared statement against provided parameters?

**Comment by vietj** [comment]
have you tried the 0.10.2 release ? there was missing tuple validation in some cases

**Comment by hfgbarrigas** [comment]
sorry, 0.10.2 fixes the issue. Thank you!
