### ISSUE TITLE
Array issue

### ISSUE THREAD

**Issue by hfgbarrigas** [reactiverse/reactive-pg-client#169]
Though the [issue](https://github.com/reactiverse/reactive-pg-client/issues/160) is closed, still getting the error.

Query:
`SELECT * FROM table WHERE attribute in ($1)`

Tuple variants:
1.
`Tuple tuple = Tuple.tuple();
  entities.forEach(e -> tuple.addString(e.getProviderId()));`
`error: io.vertx.core.impl.NoStackTraceThrowable: Values [5b8d0f4478482d6f05255fad5f22f05a, 5b8553e1a776c5ac0356c0bc6d211b0a, 5b855484ed288888030137c18f6362a5, 5b85545040112d8803a497d83042b9b5, 5b85544c40112d8803a4979acac4148a] cannot be coerced to [String] `

2.
`Tuple.of(StringArrayHere)`
`error: io.vertx.core.impl.NoStackTraceThrowable: Values [[Ljava.lang.String;@5df318d1] cannot be coerced to [String]`

3.
`Tuple.tuple().addStringArray(providerIds)`
`io.vertx.core.impl.NoStackTraceThrowable: Values [[Ljava.lang.String;@3cd91890] cannot be coerced to [String]`

Is the fix coming out on 0.10.3?

**Comment by vietj** [comment]
can you provide a reproducer ?

**Comment by hfgbarrigas** [comment]
Sure. Though, running the following should reproduce the error:

```
connection.preparedQuery(
    "SELECT * FROM my_table WHERE table_attribute IN ($1)",
    CHOOSE_ONE_OF_TUPLE_VARIANTS_SHOWN,
    mapping(this::::rowMapper,toList()), 
    ar -> {}
)
```

**Comment by hfgbarrigas** [comment]
Here's a simple test for version 0.10.2:

```
@Test
public void testStandalone() {
        TestSuite.create("suite")
                .test("array_test", ctx -> {
                    Async async = ctx.async();
                    PgPool pool = PgClient.pool(new PgPoolOptions(new PgPoolOptions()
                            .setUser("user")
                            .setPassword("password")
                            .setDatabase("database")));
                    try {
                        pool.preparedQuery(
                                "SELECT * FROM table WHERE attribute IN ($1)",
                                Tuple.tuple().addStringArray(new String[]{"a", "b", "c"}),
                                mapping((Function<Object, Object>) t -> t, toList()),
                                arr -> {
                                    if (arr.failed())
                                        ctx.fail(arr.cause());
                                    async.complete();
                                }
                        );
                        async.await(4000);
                    } finally {
                        pool.close();
                    }
                }).run(new TestOptions().addReporter(new ReportOptions().setTo("console")));
    }
```

**Comment by vietj** [comment]
@hfgbarrigas can you give the schema you used for this reproducer ?

**Comment by hfgbarrigas** [comment]
@vietj here's the original table I was using. The  attribute is provider_id
```
CREATE TABLE webhooks (
  id          SERIAL8 PRIMARY KEY,
  provider_id VARCHAR(256) NOT NULL,
  provider    VARCHAR(256) NOT NULL,
  data        JSONB        NOT NULL
);

CREATE UNIQUE INDEX webhooks_provider_id_uindex
  ON webhooks (provider_id);
CREATE INDEX webhooks_gin_id_index
  ON webhooks USING GIN ((data -> 'id'));
CREATE INDEX webhooks_gin_transfer_index
  ON webhooks USING GIN ((data -> 'transfer'));
CREATE INDEX webhooks_gin_hash_index
  ON webhooks USING GIN ((data -> 'hash'));
```

**Comment by vietj** [comment]
@atvictor your code seems to not depend on table, so it looks great for testing

**Comment by vietj** [comment]
@hfgbarrigas a complete reproducer as a project would be great

**Comment by vietj** [comment]
@atvictor so here is what I can see when I run your failing case

`"select 1 where 1 in ($1)"`

defines a prepared query parameter `$1` as type `INT4` and not as an array type

so it seems to me that there is no bug in the client

that being said I would be curious to know how this particular query runs on other clients and how they are able to use the array of integer in this case or if they fail.

**Comment by atvictor** [comment]
Yes I'm a bit confused about that.

By the way, `select 1 where 1 in ($1::int[])` also fails, but `select 1 where 1 = any ($1)` works.

The PostgreSQL protocol seems to allow the client to send parameters types (see the `Parse (F)` message here https://www.postgresql.org/docs/10/static/protocol-message-formats.html).

And `reactive-pg-client` seems to have handled that in the past (see https://github.com/reactiverse/reactive-pg-client/blob/master/src/main/java/io/reactiverse/pgclient/impl/codec/encoder/MessageEncoder.java#L225).

But yes, I think testing other clients could be a good idea, I will try to test that.

**Comment by atvictor** [comment]
Ok, I tried the JDBC PostgreSQL driver and it fails too.

```
Class.forName("org.postgresql.Driver");
Connection c = DriverManager.getConnection("jdbc:postgresql://localhost/db?user=postgres");
PreparedStatement st = c.prepareStatement("SELECT 1 WHERE 1 IN (?)");
st.setArray(1, c.createArrayOf("INT4", new Integer[] { 1, 2 }));
```

With the exception `org.postgresql.util.PSQLException: ERROR: operator does not exist: integer = integer[]`.

But this query works `SELECT 1 WHERE 1 = ANY (?)`.

So maybe I miss something here...

**Comment by vietj** [comment]
yes that was my point @atvictor , the protocol will tell the client what it expects and the developer needs to provide an argument that is compatible with what postgres will accept

**Comment by vietj** [comment]
can we close this issue @atvictor @hfgbarrigas ?

**Comment by atvictor** [comment]
For me it's ok, many thanks !

But there may be a regressions (not linked to this issue) from 0.10.1 to 0.10.2 (the third test fails in 0.10.2 but works 0.10.1: https://github.com/atvictor/reactive-pg-client/commit/4b9e2ae204f2c26e77eaaaab1215c18cf3353bb8)

**Comment by hfgbarrigas** [comment]
makes sense, feel free to close it. thanks

**Comment by vietj** [comment]
can you provide a precise standalone test for this regression as a PR ?

**Comment by atvictor** [comment]
There it is: https://github.com/atvictor/reactive-pg-client/blob/master/src/test/java/io/reactiverse/pgclient/ParametersTest.java

It fails with `Values [1, null] cannot be coerced to [Integer, Integer]` but was working before.

**Comment by vietj** [comment]
thanks, I'll look into it asap

**Comment by vietj** [comment]
@atvictor this commit should fix the issue https://github.com/reactiverse/reactive-pg-client/issues/170

**Comment by atvictor** [comment]
Yep it works, thank you very much!
