### ISSUE TITLE
Sysout for unknown columns would impact performance

### ISSUE THREAD

**Issue by sumitsrv** [reactiverse/reactive-pg-client#173]
https://github.com/reactiverse/reactive-pg-client/blob/31e7d79db8a2bbaeceb285405e3d1494cc81ca41/src/main/java/io/reactiverse/pgclient/impl/codec/DataType.java#L116

With high volume requests Sysout for the unknown columns would generate unnecessary huge volumes of data log for Stdout.

**Comment by vietj** [comment]
I agree it should be fixed, however in practice it should not happen often. Have you experienced performance issue with it ?

**Comment by sumitsrv** [comment]
Yes, as the requirement I am handling is a single query on a column of Unknown type. QPS is 40k, 24x7. Do not have the benchmarks yet, will come up with and share. Additionally too much of unnecessary data is being logged as mentioned.

**Comment by vietj** [comment]
@sumitsrv ok, you can provide a patch to use Vertx logger instead and we will make a release fixing this issue for you

**Comment by sumitsrv** [comment]
Sure, will do.

**Comment by sumitsrv** [comment]
I see a few of them in DataTypeCodec as well. Should I update those as well?

**Comment by sumitsrv** [comment]
Done

**Comment by vietj** [comment]
thanks for the contribution
