### ISSUE TITLE
RowResultDecoder does not correctly decode empty text arrays

### ISSUE THREAD

**Issue by AlxGDev** [reactiverse/reactive-pg-client#175]
I have a table where the column types are something like bigint[] | varchar(255). When trying to retrieve the entries in those columns in that order, I noticed that the values of the varchar(255) column would be empty (empty String) in the Row object, even though they aren't empty in the database. If I accessed the columns the other way around (first the text, then array), I would get the values as expected.

When trying to make a reproducer, I could not reproduce the issue, however I ran into a different one, which I suspect has the same root cause. When accessing a bigint[] or integer[] before a varchar/text field, the RowResultRecorder throws an indexOutOfBoundException:
 `readerIndex(100) + length(4) exceeds writerIndex(101): PooledUnsafeDirectByteBuf(ridx: 100, widx: 101, cap: 496) at io.reactiverse.pgclient.impl.RowResultDecoder.decodeRow(RowResultDecoder.java:73)`
When the varchar/text field is first in the SELECT query or when the array is null this issue does not occur.
I created a reproducer project here: https://github.com/AlxGDev/PgClientIssue175Reproducer

**Comment by vietj** [comment]
thanks @AlxGDev

**Comment by AlxGDev** [comment]
@vietj Yes, it is fixed. Thank you!

**Comment by vietj** [comment]
thank you for your reproducer, it helped a lot to find this issue.
