### ISSUE TITLE
Negative length while decoding binary Text

### ISSUE THREAD

**Issue by counter567** [reactiverse/reactive-pg-client#176]
I found a bug where in the function decodeRow(int len, ByteBuf in) on line 73 the length that is read is -1452458886. As I am only a Software Engineering student please tell me what information you also need to resolve the bug.
Here are some values of the debugging windows that might be interesting:
len = 13
in = "PooledUnsafeDirectByteBuf(rdix: 5163, wdix:5263, cap: 16384)"
row.size = 10
c = 10
columnDesc = "Column{dataType=TEXT, dataFormat=BINARY, length=-1, typeModifier=-1}"

https://www.postgresql.org/docs/9.3/static/protocol-message-formats.html

DataRow (B)

the only negative value could be -1.

Thats what I found in the protocol.

**Comment by vietj** [comment]
@counter567 can you provide a bug that reproduces the issue ?

**Comment by counter567** [comment]
Well I'm now at a point where the decoding of the text doesnt seem to be the exact problem, it looks more like somethings wrong with the decoding in general, cause while debugging I found out that the read length attribute of an int4 array is 1280530769 or 1668827958 or 1766348151 and then suddenly 16 and after that it is -1452458886. The length of the arrays are around 1-3 integers.
Unfortunately when I try to reproduce the Bug with a clean schema and a setup script it doesnt happen. But ill test some more.

**Comment by counter567** [comment]
@vietj Now I have a sql script and code that reproduces the issue.
[setup.txt](https://github.com/reactiverse/reactive-pg-client/files/2392059/setup.txt)


`import io.reactiverse.pgclient.*;
import io.vertx.core.AbstractVerticle;
import io.vertx.core.Vertx;

import java.util.ArrayList;
import java.util.List;

public class Main extends AbstractVerticle {

    public static void main(String[] args){
        Vertx.vertx().deployVerticle(new Main());
    }
    @Override
    public void start(){
        try {
            PgPool pgPool = PgClient.pool(vertx, createOptions());
            pgPool.getConnection(connection -> {
                connection.result().query(vertx.fileSystem().readFileBlocking("setup.txt").toString(), pgRowSetAsyncResult -> {

                    connection.result().preparedQuery("SELECT uuid, reference, name, days, home, sd, refids, it, ut, tv FROM cust5.test;",result -> {
                        List<Object> values = new ArrayList<>();
                        PgIterator iterator = result.result().iterator();
                        while (iterator.hasNext()) {
                            Row pgRow = iterator.next();
                            List<Object> row = new ArrayList<>();
                            for (String dtKey : new String[]{"reference", "addendum", "days", "name", "home", "uuid", "tv", "it", "ut", "sd", "sd"}) {
                                row.add(pgRow.getValue(dtKey));
                            }
                            values.add(row);
                            System.out.println("test");
                        }
                    });
                });
            });

        }catch(Exception e){
            e.printStackTrace();
        }

    }


    private PgPoolOptions createOptions() {
        PgPoolOptions options = new PgPoolOptions();

        return options;
    }
}
`

**Comment by vietj** [comment]
thanks I will investigate asap

**Comment by vietj** [comment]
@counter567 

with 0.10.3 I get:

```
java.lang.OutOfMemoryError: Java heap space
	at java.nio.HeapCharBuffer.<init>(HeapCharBuffer.java:57)
	at java.nio.CharBuffer.allocate(CharBuffer.java:335)
	at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:677)
	at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1220)
	at io.netty.buffer.AbstractByteBuf.getCharSequence(AbstractByteBuf.java:494)
	at io.netty.buffer.AbstractByteBuf.readCharSequence(AbstractByteBuf.java:499)
	at io.reactiverse.pgclient.impl.codec.DataTypeCodec.binaryDecodeTEXT(DataTypeCodec.java:728)
```

With the latest snapshot I get a correct result, I suspect that you are hitting an issue that was solved when fixing https://github.com/reactiverse/reactive-pg-client/issues/175 .

So can you give a test with the latest snapshot deployed in Sonatype OSS repository ?

it contain fixes for query text decoding and thus

**Comment by counter567** [comment]
Yeah it is working with the 0.10.4-20180920.115800-9 thank you very much.
