### ISSUE TITLE
Any way to execute SYNC query ?

### ISSUE THREAD

**Issue by abcfy2** [reactiverse/reactive-pg-client#178]
Sometimes I need to get some configs from PostgreSQL. Than means I must wait for query result then go to next steps.

Is there any way to execute SYNC query?

**Comment by vietj** [comment]
what do you mean by SYNC query ?

**Comment by vietj** [comment]
ah you mean a synchronous API to perform a query

**Comment by abcfy2** [comment]
Yes. I need to wait the query result. So I need the synchronous API.

**Comment by vietj** [comment]
in this case you could use a CompletableFuture and complete it with the asynchronous result, of course this should not run in a vertx thread

**Comment by abcfy2** [comment]
Thanks.
