### ISSUE TITLE
Type handling not lenient enough

### ISSUE THREAD

**Issue by marcust** [reactiverse/reactive-pg-client#179]
So I was trying to integrate jOOQ with reactive-pg-client, because I'm playing around with possible project setups. 

A problem that I encountered is that jOOQ strongly believes that the `OFFSET` and `LIMIT` parameters are `Integer`, whereas this client sees an `INT8` and expects a `Long`.

I did some magic now (https://github.com/marcust/jzenith/blob/master/jzenith-postgresql/src/main/java/org/jzenith/postgresql/PostgresqlClient.java#L96-L135) in order to avoid that, but I think if there is a type that is easily widened like an `Integer` to a `Long` that should be handled internally in the pg-client. 

I would have created a PR but I'm not sure what the best approach is, because the whole type mapping is rather 1 on 1 and I don't know what a good approach would be to make that more dynamic.

**Comment by vietj** [comment]
@marcust can you check with the latest snapshot ?

**Comment by marcust** [comment]
@vietj works with my test suite, so seems to be fine.

**Comment by vietj** [comment]
do you have integration with jooq ? perhaps you could contribute this integration in this project ?

**Comment by marcust** [comment]
No, not really an integration. I don't think that jOOQ does real async yet, from what I've seen they postpone it from version to version. I have some glue code between jOOQ, the JDBC Postgres driver and the reactive client that translates the queries to pure Postgres SQL and then just executes them (https://github.com/marcust/jzenith/blob/master/jzenith-postgresql/src/main/java/org/jzenith/postgresql/PostgresqlClient.java)
