### ISSUE TITLE
Pool does not handle connection failure correctly 

### ISSUE THREAD

**Issue by marcust** [reactiverse/reactive-pg-client#180]
While writing health checks I realized that the pool does not handle connection failure correctly. 

To try that out you can check out https://github.com/marcust/jzenith and do the following steps
```sh
cd jzenith-example/jzenith-example-postgres-plugin/ 
mvn docker:start
curl localhost:8080/health
```
that should give you a 200 and a UP message. When you now stop the container with `docker stop <container id>` and do more curls you will get first a message that says `Connection refused: localhost/127.0.0.1:5433` and the second time a timeout due to the fact that nothing is coming out of the `PgPool` instance anymore. That also does not recover, meaning that when you restart the container the pool stays broken.

A quick debugging showed that the pool is at capacity (4) but somehow not getting rid of the broken connections.

**Comment by vietj** [comment]
I will have a look

**Comment by vietj** [comment]
when I try this, I get connection refused from cURL.

**Comment by vietj** [comment]
I'm assuming I'm missing a `mvn package` + run the fat jar.

**Comment by vietj** [comment]
I found the issue, thanks for reporting it's a legit one :-)

**Comment by vietj** [comment]
I will do quickly a bug fix release

**Comment by vietj** [comment]
connection pools are hell to get right :-)
