### ISSUE TITLE
Usage of "in" rxPrepare and how should I send the Tuple in createStream method.

### ISSUE THREAD

**Issue by smahad786** [reactiverse/reactive-pg-client#186]
I am able to write the query with "=" and LIKE. However, how do I do this with "in" parameter - for the example below. What should I supply as the Tuple in the createStream method?

```
Flowable<Row> flowable = pool.rxGetConnection()
  .flatMapPublisher(conn -> conn.rxPrepare("SELECT * FROM users WHERE first_name LIKE $1")
    .flatMapPublisher(pq -> {
      // Fetch 50 rows at a time
      PgStream<Row> stream = pq.createStream(50, Tuple.of("julien"));
      return stream.toFlowable();
    }));
```

**Comment by vietj** [comment]
I think what you did is the correct way, what happened ?

**Comment by smahad786** [comment]
When I use IN parameter, I did not know how to supply the values in the createStream. I wanted to do something like select * from tbl where id in ['key1', 'key2', 'key3']; I had to construct the query and did it a bit differently to make it work for this week [see below]. I did not want to construct the query with "OR".
return client
            .rxQuery(createSQLQuery(keys))
            .flatMapPublisher(
                    pgRowSet -> {
                      PgIterator iterator = pgRowSet.iterator();
                      while (iterator.hasNext()) {
                        Row row = iterator.next();
                        list.add(convertRowToObject(row));
                      }
                      return Flowable.fromIterable(list);
                    });

**Comment by vietj** [comment]
@smahad786 you should not use the `IN` operator, please have a look at https://stackoverflow.com/questions/178479/preparedstatement-in-clause-alternatives

**Comment by vietj** [comment]
it's not clear if your issue is because of `IN` operator or something else, could you clarify ?

**Comment by vietj** [comment]
closing this issue in the meantime
