### ISSUE TITLE
Source code for rxjava and reactivex API variants missing from -sources.jar

### ISSUE THREAD

**Issue by karltk** [reactiverse/reactive-pg-client#192]
AFAICT, the source code for the rxjava and reactivex variants of the API is no longer included in the sources jar.

```
$ jar tvf ./m2/repository/io/reactiverse/reactive-pg-client/0.10.6/reactive-pg-client-0.10.6.jar | grep rxjava | wc -l
47

$ jar tvf ./m2/repository/io/reactiverse/reactive-pg-client/0.10.6/reactive-pg-client-0.10.6-sources.jar | grep rxjava | wc -l
0
```

I find that having the source code is very handy for development, as it brings additional understanding above and beyond what the javadocs provide. 

Any chance the code can be put back into future releases? It seems to have been present in the past, c.f. #48 .

**Comment by vietj** [comment]
it seems unfortunate indeed and an issue, it will be resolved in the next version.
