### ISSUE TITLE
citext support

### ISSUE THREAD

**Issue by arrowwood49** [reactiverse/reactive-pg-client#196]
Does pg-client support citext type https://www.postgresql.org/docs/10/static/citext.html?

I can insert successfully with citext type but can't read the column with citext type.  `io.reactiverse.reactivex.pgclient.Row`  methods getValue() and getString() both returns null.

Thanks

**Comment by vietj** [comment]
do you know if that's possible to install it in the testing docker image of this project ?

**Comment by vietj** [comment]
do you know how that works with the Postgresql JDBC driver ? that would help understand how it's handled there.

**Comment by EmadAlblueshi** [comment]
Yes CITEXT is not supported yet

**Comment by vietj** [comment]
does the citex have a stable type OID ?

**Comment by vietj** [comment]
would it be possible to have a docker image that supports this extension for testing ?

**Comment by EmadAlblueshi** [comment]
We should find the OID and in docker I think it’s possible to install the extension for testing but I’m not sure if it needs external package or simply enable it like pre installed extensions

**Comment by arrowwood49** [comment]
citext can be installed from standard Postgres extension.

The following creates the extension with test table in docker/postgres/resources/create-postgres.sql
```
CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;
DROP TABLE IF EXISTS test_citext;
CREATE TABLE test_citext (id integer, name citext);

```
