### ISSUE TITLE
StreamQuery with transaction

### ISSUE THREAD

**Issue by arrowwood49** [reactiverse/reactive-pg-client#197]
RxJava2 example [here](https://reactiverse.io/reactive-pg-client/guide/java/index.html) shows how to create stream query using connection. How do I create stream using PgTransaction class. I can't find method on `io.reactiverse.reactivex.pgclient.PgTransaction` class to get PgPreparedQuery or PgStream.

Thanks

**Comment by vietj** [comment]
we will add this method in the next version to prepare a query from a transaction

**Comment by vietj** [comment]
in this API, you will only need to change `pool.rxGetConnection()` by `pool.rxBegin()` or call begin within a transaction. That being said now you can begin a transaction from a connection and get the prepared query on from the connection but it's less intuitive.

**Comment by arrowwood49** [comment]
In our implementation, we create the transaction and pass that to other classes and methods which then executes the sql using the same transaction object. So it is inconvenient to change all those implementation. As a workaround, we are not using the prepared sql and not using the streaming query when working with transaction.

**Comment by arrowwood49** [comment]
> we will add this method in the next version to prepare a query from a transaction

@vietj When do you think next version will be released?

**Comment by vietj** [comment]
it has been released
