### ISSUE TITLE
SSL upgradefuture failure is not properly handled

### ISSUE THREAD

**Issue by BillyYccc** [reactiverse/reactive-pg-client#206]
#### Version
0.10.7
#### How to reproduce:
1. Set up a postgres server without SSL on.
2. Connect with the server using client with ssl option on.
3. AsyncResult failure is never handled.

#### Simple Code:
```
import io.reactiverse.pgclient.PgClient;
import io.reactiverse.pgclient.PgConnectOptions;
import io.reactiverse.pgclient.PgConnection;
import io.vertx.core.Vertx;

public class Reproducer {
  public static void main(String[] args) {
    Vertx vertx = Vertx.vertx();

    PgConnectOptions options = new PgConnectOptions()
      .setSsl(true)
      .setHost("localhost")
      .setPort(5432)
      .setUser("postgres")
      .setPassword("password")
      .setDatabase("postgres");

    PgClient.connect(vertx, options,
      ar -> {
        if (ar.succeeded()) {
          System.out.println("success");
          PgConnection pgConnection = ar.result();
          System.out.println("is SSL?" + pgConnection.isSSL());
        } else {
          //FIXME this is never called
          System.out.println("fail");
        }
      });

    // blocking the main method to avoid exit
    try {
      Thread.sleep(5000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
  }
}
```

**Comment by BillyYccc** [comment]
Currently SSL upgrade failure is propagated to the next ChannelHandler in ChannelPipeline:
https://github.com/reactiverse/reactive-pg-client/blob/a79050946983236c244aabcdac28c62db57ac97a/src/main/java/io/reactiverse/pgclient/impl/codec/decoder/InitiateSslHandler.java#L65-L72

exceptionCaught here could not catch the SSL upgrade failure and report to upgradeFuture.
https://github.com/reactiverse/reactive-pg-client/blob/a79050946983236c244aabcdac28c62db57ac97a/src/main/java/io/reactiverse/pgclient/impl/codec/decoder/InitiateSslHandler.java#L76-L83

**Comment by vietj** [comment]
I will have a look soon

**Comment by vietj** [comment]
can you provide a patch with a test for this ?

**Comment by BillyYccc** [comment]
Can you please review https://github.com/reactiverse/reactive-pg-client/pull/215?
