### ISSUE TITLE
SSL mode support

### ISSUE THREAD

**Issue by BillyYccc** [reactiverse/reactive-pg-client#207]
https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-SSLMODE
https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-PROTECTION

**Comment by BillyYccc** [comment]
I have made some progress to build a prototype for this in https://github.com/BillyYccc/vertx-pg-client/tree/feature/sslmode.

Before going on,there are some issues we should solve:
1. SSL upgrade future failure handling mentioned in https://github.com/reactiverse/reactive-pg-client/issues/206.
2. Currently embedded postgres for unit testing only supports SSL, maybe we should set up a seperated non-SSL embedded postgres for some unit tests related to SSL stuff?

**Comment by pratikpparikh** [comment]
@BillyYccc for 2. can you not just use the docker setup as an external Postgres?

**Comment by BillyYccc** [comment]
I think using docker may not work because we didn't set up a docker environment in Travis for now and for some reasons we chose to use embedded postgres instead of testcontainer before.
The issue here is we need both two kinds of postgres at the same time in the unit tests (i.e make the embedded postgres ssl settings configurable).

**Comment by pratikpparikh** [comment]
@BillyYccc, it might be better to configure Travis with docker and use maven docker plugin to start and stop the remote server.  I think we will have to refactor the test cases to work with both standalone and embedded.

**Comment by mbit0815** [comment]
@BillyYccc nice work. Do you have an idea when this will be merged to master?

**Comment by BillyYccc** [comment]
@mbit0815 I have no exactly delivery time here, but it should not be far away, just some more work to be finished.

**Comment by anilkan** [comment]
Thanks @BillyYccc. Is there any news about merging ?

**Comment by vietj** [comment]
it's being reviewed, we are almost done

**Comment by BillyYccc** [comment]
@leenux I think Julien can do a release soon after the PR is merged.

As for URI format, the branch only supports `sslmode` parameter, currently cert and key parameters are not supported but we can do that.
You can try the branch directly and give me some feedback  :-).

**Comment by vietj** [comment]
it can be released soonish

**Comment by anilkan** [comment]
Hi @vietj, do you have any plan to push 0.11.2 to maven repository ?

**Comment by vietj** [comment]
yes soon @anilkan
