### ISSUE TITLE
Example for Kotlin throws compilation errors

### ISSUE THREAD

**Issue by nobleach** [reactiverse/reactive-pg-client#213]
Using this example from the Kotlin docs page:
```kotlin
var options = PgPoolOptions(
  port = 5432,
  host = "the-host",
  database = "the-db",
  user = "user",
  password = "secret",
  maxSize = 5)
```
Throws the following error
```
None of the following functions can be called with the arguments supplied:
public constructor PgPoolOptions() defined in io.reactiverse.pgclient.PgPoolOptions
public constructor PgPoolOptions(p0: PgConnectOptions!) defined in io.reactiverse.pgclient.PgPoolOptions
public constructor PgPoolOptions(p0: PgPoolOptions!) defined in io.reactiverse.pgclient.PgPoolOptions
public constructor PgPoolOptions(p0: JsonObject!) defined in io.reactiverse.pgclient.PgPoolOptions
```
Is there something undocumented that I'll need to do to pass these args?

**Comment by nobleach** [comment]
That appears to be an unresolved import. (and throws `java.lang.ClassNotFoundException`)

I am currently importing: `import io.reactiverse.pgclient.*` And connecting via:
```
  // Connection URI
  var connectionUri = "postgresql://myuser:password@localhost:5432/mydb"
  // Create the client pool
  var client = PgClient.pool(connectionUri)
```
This appears to work. Is there a different package that should be used for Kotlin?

**Comment by vietj** [comment]
I think it should be io.reactiverse.kotlin.pgclient

**Comment by nobleach** [comment]
Very strange. That throws `Unresolved reference: kotlin`.

**Comment by vietj** [comment]
I think it's because we don't provide kotlin classes anymore (regression).

**Comment by vietj** [comment]
so we should fix the build and make a new minor release

**Comment by vietj** [comment]
the class exist in thep roject though. I think you can take the code and copy/paste in your project in the meantime

**Comment by nobleach** [comment]
Thank you so much for looking at it! I can use the connectionUri for now.

**Comment by vietj** [comment]
it should be present in 0.10.10-SNAPSHOT for you to verify

**Comment by nobleach** [comment]
Thank you!
