### ISSUE TITLE
Having issue with using an array as query arguments on prepared statements

### ISSUE THREAD

**Issue by huntj88** [reactiverse/reactive-pg-client#244]
I've seen other issues with sending arrays as query params, but they are all closed and the problem still looks like it's there.

my query takes in an array of strings and then fails with the message 

> [[Ljava.lang.String;@141c4c78] cannot be coerced to [String]

```
create table notes
(
  id        char(36)      not null
    constraint notes_pk
      primary key,
  rich_text varchar(2000) not null
);
```

`SELECT * FROM notes WHERE id IN ($1);`

```
val args = noteIds.toTypedArray().let { 
    Tuple.tuple().addStringArray(it) 
}
```

```
pool.preparedQuery(query, args) { rowsAsync ->
    // other code
}
```

**Comment by huntj88** [comment]
I tried changing everything to the uuid type rathing than holding it in a char(36), but i got the same result

`[[Ljava.util.UUID;@394972bf] cannot be coerced to [UUID]`

**Comment by vietj** [comment]
@huntj88 this is because the type of `$1` is String and is not `String[]`, this is actually a postgres issue and not an issue of this client

**Comment by vietj** [comment]
I think somebody raise a similar issue in this tracker

**Comment by vietj** [comment]
you nee to change your query to `select 1 where 1 = any ($1)`, see this issue https://github.com/reactiverse/reactive-pg-client/issues/169#issuecomment-418385715
