### ISSUE TITLE
is there a reason why io.reactiverse.reactivex.pgclient.PgIterator isn't an Iterator ?

### ISSUE THREAD

**Issue by djocal** [reactiverse/reactive-pg-client#250]
whereas io.reactiverse.pgclient.PgIterator is one ?
if no reason, do you have any concern i submit a change making it one ? 
thanks

**Comment by vietj** [comment]
actually it is useful because it allows code generation in vertx (for rxjava for instance), also it types the iterator to be a `Iterator<Row>` so for now it should be kept
