### ISSUE TITLE
Question: How to use CTE with prepareBatch

### ISSUE THREAD

**Issue by smahad786** [reactiverse/reactive-pg-client#256]
I tried to use PostGres CTE with reactive-pg-client and I am not getting the desired result. I have a small table USERS (id UUID, name varchar(20), age int ) all not nulls and id is the PK. 

Does pg-reactive client work with CTE? It works for single inserts but when I use List of tuples, I don't get desired result.

I wanted to do a batch insert using List<Tuple> and wanted to know existence of duplicates and return the id for the duplicates. I did the following SQL 

with CTE_NAME AS 
(
INSERT INTO USERS (id, name, age) VALUES ($1, $2, $3) on conflict (id) do NOTHING returning id
)
SELECT id as result from USERS  WHERE id = $1 and id NOT IN (select id from CTE_NAME)

List<Tuple> batch = new ArrayList<>();
        batch.add(Tuple.of(UUID.fromString("d1c0f6bd-759e-4b23-bdd0-04c634d3dc38"), "Jack", 10));
        batch.add(Tuple.of(UUID.fromString("9c6ac928-b3a4-46d6-ae18-55749143dea1"), "Jill", 11));
        batch.add(Tuple.of(UUID.randomUUID(), "Leo", 1));       
client.preparedBatch(sql_cte.toString(), batch, ar -> {

            if (ar.succeeded()) {
                PgIterator iterator = ar.result().iterator();
                while (iterator.hasNext()) {
                    Row next = iterator.next();
                    System.out.println("next result " + next.getUUID("result"));
                }

            } else
                System.out.println(ar.cause().getMessage());
        });

Any help please?

**Comment by vietj** [comment]
there are not reasons it should not work, have you checked it works with other clients ?

the batch execution will execute the statement for each row.

**Comment by vietj** [comment]
if that works with other clients (like JDBC) can you provide a reproducer project with such clients so we can compare with this client ?

**Comment by smahad786** [comment]
Is my approach correct?

**Comment by smahad786** [comment]
Closed.
