### ISSUE TITLE
Converting PgRowSet to List<JsonObject>

### ISSUE THREAD

**Issue by mystdeim** [reactiverse/reactive-pg-client#259]
Is it possible to converting PgRowSet to List<JsonObject>? I'm planning to migrate from jdbc to reactive-pg-client but I have many places where I converting resultset to List<JsonObject> or list of Pojos

**Comment by BillyYccc** [comment]
You can have a try on the `java.util.stream.Collector` API of this client, there is an example in https://github.com/reactiverse/reactive-pg-client/blob/f04bdb41c0ed535c20a098e2759b02de68c4085b/src/main/java/examples/Examples.java#L760
