### ISSUE TITLE
PreparedQuery order by using position references 

### ISSUE THREAD

**Issue by limadelrey** [reactiverse/reactive-pg-client#261]
Hello everyone,

I'm using rxPreparedQuery method in order to get user's information in an asynchronous way. Just like I was using a PreparedStatement I'm using references in order to avoid SQL injection attacks. 

Query: `SELECT u.* FROM user u WHERE u.name = $1 ORDER BY $2 DESC LIMIT $3 OFFSET $4` 
Tuple: `[limadelrey, u.name, 50, 0]`

Using this example it is possible to filter and to limit the results. However, for some reason I can't order using position references at the moment I'm writing this issue.

Is it a mistake of mine? Or is it impossible to use position references to order results?

Thanks in advance.

**Comment by vietj** [comment]
have you tried this query with another client to compare ?

**Comment by vietj** [comment]
closing as it's a question

**Comment by limadelrey** [comment]
I haven't tried because this query syntax and tuple API are specific to reactive-pg-client. However, I think that the usual PreparedStatement with JDBC client doesn't allow to order with a reference either.

**Comment by vietj** [comment]
I am not a specialist of ordering this way, can you elaborate what is so specific ?
