### ISSUE TITLE
Please clarify benchmark

### ISSUE THREAD

**Issue by lemoony** [reactiverse/reactive-pg-client#262]
The Readme states that this driver is Ranked #1 in the TechEmpower Benchmark Round 15 Single query benchmark. When looking up the benchmark, the driver listed at #1 is "vertx-postgres". The latter, however, is apparently based on this driver:

https://github.com/jasync-sql/jasync-sql

So please clarify the statement.

**Comment by BillyYccc** [comment]
The benchmark code is open-sourced and it's quite straightforward to check the dependency in https://github.com/TechEmpower/FrameworkBenchmarks/blob/round15/frameworks/Java/vertx/pom.xml
