### ISSUE TITLE
Is it thread safe? Should I share it in mutiple threads?

### ISSUE THREAD

**Issue by cpdyj** [reactiverse/reactive-pg-client#263]
Hello,
I want to use in Vert.x. Should I share it in mutiple `Verticle`(include `WorkVerticle`)?  
Is there any best practice?
Thank you.

**Comment by vietj** [comment]
that's a good question

you can share it in multiple verticles, that being said I have doubts about worker verticles and I believe tests should be conducted with worker to figure this out.

**Comment by cpdyj** [comment]
Thank you. I will have a look. And... Is there anything to notice if I use it with Vert.x?
@vietj

**Comment by vietj** [comment]
no, it shouldwork well with and without vertx.

if you use with vertx, it will respect vertx threading model and will call you back on the right event loop
