### ISSUE TITLE
Unable to access between docker services

### ISSUE THREAD

**Issue by batbayar-su** [reactiverse/reactive-pg-client#264]
Using this library in vertx project and it is using docker postgres as external database. It is working fine while running vertx project in my machine. 

But when put the project in docker, it returns `io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(..) failed: Connection refused: localhost/127.0.0.1:5432`

**Comment by BillyYccc** [comment]
Can you share more details? I think it may be related to your Docker configuration.

**Comment by batbayar-su** [comment]
So sorry you were right. 😢🙇‍♂️

**Comment by majsna** [comment]
@batbayar-su can you share what was wrong with your docker configuration? I'm having a similar issue.
