### ISSUE TITLE
Transactions between multiple classes

### ISSUE THREAD

**Issue by volnei** [reactiverse/reactive-pg-client#267]
There are any pattern to keep multiple data services running in same transaction without holding the connection/pool instance?

Example:

```java
// open transaction
tx.begin();
// the follow internal services code must run on same transaction
dataService1.save(object1); 
dataService2.save(object2);
dataService3.save(object3);
// and then close transaction
tx.commit();
```

Using the code above there are no guarantees that queries will be executed on same connection, right?

Thanks!!

**Comment by vietj** [comment]
yes it will be on the same connection.

you can only call begin() on an existing connection which means you need to hold it for the duration of the transaction.
