### ISSUE TITLE
Akka Stream integration

### ISSUE THREAD

**Issue by rowlandwatkins** [reactiverse/reactive-pg-client#271]
Hi folks,

I'm looking for a replacement to the postgresql-async Netty driver and found this one, which is very cool. I've taken a look at the rxJava2 API and I've been attempting to integrate with Akka Streams with limited success.

Integration between rxJava and Akka Streams seems fine when we're publishing data (select), but becomes problematic when we just want to insert data and end the stream. Based on the Java docs I've found the following, which looks promising:

```
Completable completable = pool
  .rxBegin()
  .flatMapCompletable(tx -> tx
    .rxQuery("INSERT INTO Users (first_name,last_name) VALUES ('Julien','Viet')")
    .flatMap(result -> tx.rxQuery("INSERT INTO Users (first_name,last_name) VALUES ('Emad','Alblueshi')"))
    .flatMapCompletable(result -> tx.rxCommit()));

completable.subscribe(() -> {
  // Transaction succeeded
}, err -> {
  // Transaction failed
});
```

From what I can tell, Completable will never work as a Subscriber, so Akka Streams cannot take advantage of the above code, some it would need to be extended to accept something like Completable (which naively seems like a Future).

Akka Streams does have the handy mapAsync for such deferred computation, but normally takes a Future as input. My thought then is could a query/transaction return a Future, aside from a Handler callback?

Thanks in advance!

Cheers,

Rowland

**Comment by rowlandwatkins** [comment]
Just saw this issue: https://github.com/reactiverse/reactive-pg-client/issues/270, Single can also be wrapped as a java.util.concurrent.Future:

```
Single.just(contract)
              .map(JsonObject::mapFrom)
              .map(Json::create)
              .flatMap( foo -> pool.rxPreparedQuery(CREATE_QUERY, Tuple.of(foo)) )
              .map(ar -> uuid)
              .toFuture()
```

I'll try this, cheers!

**Comment by tsegismont** [comment]
@rowlandwatkins a `Completable` can be converted to a `Publisher`. I'm curious how that doesn't work for you?

**Comment by yieldone** [comment]
Hi @tsegismont, I'm not sure how a publisher will help, since I need a Subscriber... Or am I looking at this the wrong way?

**Comment by tsegismont** [comment]
@rowlandwatkins can't Akka streams create a subscriber from any `Publisher`?
