### ISSUE TITLE
Comparison with async mauricio driver 

### ISSUE THREAD

**Issue by nailgilaziev** [reactiverse/reactive-pg-client#94]
Dear author!
I'm not an expert in async drivers for **postgresql** and maybe I can't understand the nuances in the differences between them, so it will be great if you would bring your subjective explanation for such people as me.
In async world I know some drivers for **postgres** and most popular is  https://github.com/mauricio/postgresql-async that officially used in **vertx**.
Explain, please, what are the conceptual differences and for what tasks is your library oriented?
How mature is the project and ready for production? 
Ps. I want to start doing a project that uses **ktor** and kotlin **coroutines** with postgresql - raw sql statements and jsonb columns.
Thank you for your time!

**Comment by vietj** [comment]
I think you can use this client for any postgresql task + it supports specific PG features like notifications

**Comment by vietj** [comment]
I'm closing this issue as it's not really an issue

**Comment by nailgilaziev** [comment]
Thanks for your reply!
